version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  reviewers:
  - DirkSCGM
  ignore:
  - dependency-name: importlib-metadata
    versions:
    - 3.10.0
    - 3.4.0
    - 3.7.0
    - 3.7.2
    - 3.7.3
    - 3.9.0
    - 4.0.0
  - dependency-name: boto3
    versions:
    - 1.16.59
    - 1.16.63
    - 1.17.12
    - 1.17.17
    - 1.17.22
    - 1.17.27
    - 1.17.3
    - 1.17.33
    - 1.17.39
    - 1.17.44
    - 1.17.49
    - 1.17.53
    - 1.17.7
  - dependency-name: setuptools
    versions:
    - 52.0.0
    - 53.0.0
    - 54.0.0
    - 54.1.1
    - 54.1.2
    - 54.2.0
  - dependency-name: pandas
    versions:
    - 1.2.1
    - 1.2.2
    - 1.2.3
  - dependency-name: tqdm
    versions:
    - 4.56.0
    - 4.56.2
    - 4.57.0
    - 4.58.0
    - 4.59.0
  - dependency-name: numpy
    versions:
    - 1.19.5
    - 1.20.0
    - 1.20.1
